services:
  agora:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_MAPTILER_API_KEY: ${VITE_MAPTILER_API_KEY}
        VITE_MAPTILER_MAP_ID: ${VITE_MAPTILER_MAP_ID}
        VITE_GEOSERVER_USERNAME: ${VITE_GEOSERVER_USERNAME}
        VITE_GEOSERVER_PASSWORD: ${VITE_GEOSERVER_PASSWORD}
        VITE_GEOSERVER_BASE_URL: ${VITE_GEOSERVER_BASE_URL}
        VITE_GEOSERVER_REST_URL: ${VITE_GEOSERVER_REST_URL}
        VITE_PARCEL_DATASET_WORKSPACENAME: ${VITE_PARCEL_DATASET_WORKSPACENAME}
        VITE_PARCEL_DATASET_LAYERNAME: ${VITE_PARCEL_DATASET_LAYERNAME}
        VITE_PARCEL_DATASET_LAYERINFORMATION_URL: ${VITE_PARCEL_DATASET_LAYERINFORMATION_URL}
        VITE_AGORA_API_BASE_URL: ${VITE_AGORA_API_BASE_URL}
    ports:
      - "5175:80"
    container_name: agora
    restart: unless-stopped
